---
title: "microarray analysis"
author: "Rich Chien"
date: "October 23, 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Load packages

```{r libs}
library(affy)   
library(limma)
library(GEOquery)
library(inSilicoMerging)
```

Download GEO Raw files and unzip

```{r geo}
if(length(dir("Data/GEO/",pattern="GSE29617"))==0)
{
  getGEOSuppFiles("GSE29617", makeDirectory = TRUE, baseDir = "./Data/GEO/")
  untar("./Data/GEO/GSE29617/GSE29617_RAW.tar", exdir="./Data/GEO/GSE29617/", tar=Sys.getenv("TAR"))
}

# (optional) gunzip
cels <- list.files("./Data/GEO/", pattern = "[gz]")
sapply(paste("./Data/GEO/", cels, sep="/"), gunzip)

```

Download phenotype data from source


RMA normalization

```{r normalize}
celfiles <- system.file("extdata", package="arrays")
eset <- justRMA(phenoData=phenoData, celfile.path=celfiles)
```

Build combined database with COMBAT batch effect removal 

```{r combine}
esetlist = list(dfhcc, emc2, mainz, mda5, msk, tam, tamguyt, tamguyt2, transbig, unt, upp, vdx1, vdx3, vdxn, tabm, bc, nuv, nuv2)
memory.limit(size=6000)
combinedset = merge(esetlist, method="COMBAT")
```

When multiple probes match same gene
* take mean of all probes matching to the gene. (http://www.inside-r.org/packages/cran/WGCNA/docs/collapseRows)
* take the probe with the largest variance. (nsfilter from genefilter)

filter off dups and affy probes
```{r filter probes}

fcombinedset <- nsFilter(combinedset, require.entrez=FALSE, require.GOBP=FALSE, require.GOCC=FALSE, require.GOMF=FALSE, require.CytoBand=FALSE, remove.dupEntrez=TRUE, var.func=IQR, var.cutoff=0.5, var.filter=FALSE, filterByQuantile=FALSE, feature.exclude="^AFFX")
```
